<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="mbp.local" name="fr.eseo.atribus.dao.DaoConfigurationExceptionTest" tests="3" failures="0" timestamp="20 May 2016 20:26:06 GMT" time="0.006" errors="0">
  <testcase name="daoConfigurationExceptionString" time="0.004" classname="fr.eseo.atribus.dao.DaoConfigurationExceptionTest"/>
  <testcase name="daoConfigurationExceptionThrowable" time="0.001" classname="fr.eseo.atribus.dao.DaoConfigurationExceptionTest"/>
  <testcase name="daoConfigurationExceptionStringThrowable" time="0.001" classname="fr.eseo.atribus.dao.DaoConfigurationExceptionTest"/>
</testsuite> <!-- fr.eseo.atribus.dao.DaoConfigurationExceptionTest -->
